### ISSUE TITLE
In the main branch , download_models.sh file is errorneous. There are html contents in INTERSPEECH-T-BRNN.pcl  which comes from 403 error. So while running this command: poetry run python3 src/app.py inside docker container it is unable to load the model.  I think their is some problem while getting contents from google doc file into the .pcl file. Please fix this bug .

### ISSUE THREAD

**Issue by anubhuti24** [misharigot/chappy#11]

**Comment by misharigot** [comment]
I am no longer maintaining this project, but you are free to fork it and fix the issue of course!

**Comment by anubhuti24** [comment]
So please let me know if any of the contributors working on it.

**Comment by anubhuti24** [comment]
I can fix the issue of course, but can you please tell me about the issue a little bit, any source of issue, any starting point of the error so that I can proceed with the bug.

**Comment by misharigot** [comment]
Nobody is working on this project anymore, the last commit was over two years ago. Regarding your error, it sounds like the models that we download are no longer accessible, hence the 403.

**Comment by anubhuti24** [comment]
Yeah, that's why I am unable to download models from .sh file. This issue could only be solved if i can get the accessible google doc link . Please provide me with that or any source to solve this issue. As this is quite important right now.
